[package]
name = "devforge-auth"
version.workspace = true
edition.workspace = true

[dependencies]
devforge-shared = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
argon2 = "0.5"
password-hash = "0.5"
rand_core = { version = "0.6", features = ["std"] }
sha2 = "0.10"
hex = "0.4"
