//! Copie un fichier SQLite vers du SQL PostgreSQL (schéma + lignes).
//!
//! Les types suivent l'affinité SQLite. Une clé primaire entière devient
//! `BIGINT GENERATED BY DEFAULT AS IDENTITY` pour que les prochains INSERT
//! sans id continuent après les lignes importées.

use sqlx::sqlite::{SqliteConnectOptions, SqlitePoolOptions};
use sqlx::{Row, SqlitePool};
use std::path::{Path, PathBuf};
use std::str::FromStr;

#[derive(Debug, Clone)]
pub struct MigrationPlan {
    pub sql: String,
    pub tables: usize,
    pub rows: usize,
    pub source: String,
}

#[derive(Clone, Copy, PartialEq, Eq)]
enum ColKind {
    Int,
    Float,
    Bool,
    Bytes,
    Numeric,
    Text,
}

struct Column {
    name: String,
    kind: ColKind,
    not_null: bool,
    default_sql: Option<String>,
    pk: i64,
}

/// Fichier SQLite à importer : `DATABASE_URL=sqlite:…` s'il pointe un fichier,
/// sinon `data/app.db` (ou le premier `*.db` de `data/`) dans le workdir.
pub fn resolve_sqlite_source(
    workdir: Option<&Path>,
    database_url: Option<&str>,
) -> Option<PathBuf> {
    if let Some(url) = database_url.map(str::trim).filter(|s| !s.is_empty()) {
        let lower = url.to_ascii_lowercase();
        if lower.starts_with("sqlite:") {
            let path = sqlite_url_path(url);
            if path.is_file() {
                return Some(path);
            }
        }
    }
    let workdir = workdir?;
    let data = workdir.join("data");
    let preferred = data.join("app.db");
    if preferred.is_file() {
        return Some(preferred);
    }
    first_db_file(&data).or_else(|| first_db_file(workdir))
}

fn sqlite_url_path(url: &str) -> PathBuf {
    let rest = url.split_once(':').map(|(_, r)| r).unwrap_or(url);
    let path = rest.split('?').next().unwrap_or(rest).trim();
    PathBuf::from(path)
}

fn first_db_file(dir: &Path) -> Option<PathBuf> {
    let entries = std::fs::read_dir(dir).ok()?;
    let mut files: Vec<PathBuf> = entries
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().and_then(|x| x.to_str()) == Some("db") && p.is_file())
        .collect();
    files.sort();
    files.into_iter().next()
}

pub async fn plan_sqlite_file(path: &Path) -> Result<MigrationPlan, String> {
    if !path.is_file() {
        return Err(format!("fichier SQLite introuvable : {}", path.display()));
    }
    let opts = SqliteConnectOptions::from_str(&format!("sqlite:{}", path.display()))
        .map_err(|e| e.to_string())?
        .read_only(true);
    let pool = SqlitePoolOptions::new()
        .max_connections(1)
        .connect_with(opts)
        .await
        .map_err(|e| format!("ouverture SQLite : {e}"))?;
    let plan = plan_from_pool(&pool, &path.display().to_string()).await?;
    pool.close().await;
    Ok(plan)
}

async fn plan_from_pool(pool: &SqlitePool, source: &str) -> Result<MigrationPlan, String> {
    let tables: Vec<(String,)> = sqlx::query_as(
        r#"SELECT name FROM sqlite_master
           WHERE type = 'table'
             AND name NOT LIKE 'sqlite_%'
             AND name != '_devforge_db'
           ORDER BY name"#,
    )
    .fetch_all(pool)
    .await
    .map_err(|e| e.to_string())?;

    let mut sql = String::from("BEGIN;\n");
    let mut total_rows = 0usize;
    let mut emitted = 0usize;
    let mut inserts = String::new();

    for (name,) in &tables {
        if !safe_ident(name) {
            return Err(format!("table SQLite refusée : {name}"));
        }
        let columns = load_columns(pool, name).await?;
        if columns.is_empty() {
            continue;
        }
        sql.push_str(&create_table(name, &columns));
        sql.push_str(&create_indexes(pool, name).await?);
        let (chunk, n) = copy_rows(pool, name, &columns).await?;
        total_rows += n;
        inserts.push_str(&chunk);
        if n > 0 {
            if let Some(seq) = identity_setval(name, &columns) {
                inserts.push_str(&seq);
            }
        }
        emitted += 1;
    }

    if emitted > 0 {
        sql.push_str("SET session_replication_role = replica;\n");
        sql.push_str(&inserts);
        sql.push_str("SET session_replication_role = DEFAULT;\n");
    }
    sql.push_str("COMMIT;\n");

    Ok(MigrationPlan {
        sql,
        tables: emitted,
        rows: total_rows,
        source: source.into(),
    })
}

async fn load_columns(pool: &SqlitePool, table: &str) -> Result<Vec<Column>, String> {
    let rows = sqlx::query(&format!("PRAGMA table_info({})", quote_ident(table)))
        .fetch_all(pool)
        .await
        .map_err(|e| e.to_string())?;
    let mut columns = Vec::new();
    for row in rows {
        let name: String = row.try_get("name").map_err(|e| e.to_string())?;
        if !safe_ident(&name) {
            return Err(format!("colonne refusée : {table}.{name}"));
        }
        let ty: String = row.try_get("type").unwrap_or_default();
        let not_null: i64 = row.try_get("notnull").unwrap_or(0);
        let pk: i64 = row.try_get("pk").unwrap_or(0);
        let default_raw: Option<String> = row.try_get("dflt_value").unwrap_or(None);
        columns.push(Column {
            name,
            kind: classify(&ty),
            not_null: not_null != 0,
            default_sql: default_raw.and_then(|d| safe_default(&d)),
            pk,
        });
    }
    Ok(columns)
}

fn classify(ty: &str) -> ColKind {
    let u = ty.to_ascii_uppercase();
    if u.contains("BOOL") {
        ColKind::Bool
    } else if u.contains("INT") {
        ColKind::Int
    } else if u.contains("REAL") || u.contains("FLOA") || u.contains("DOUB") {
        ColKind::Float
    } else if u.contains("BLOB") {
        ColKind::Bytes
    } else if u.contains("NUM") || u.contains("DEC") {
        ColKind::Numeric
    } else {
        ColKind::Text
    }
}

fn pg_type(kind: ColKind) -> &'static str {
    match kind {
        ColKind::Int => "BIGINT",
        ColKind::Float => "DOUBLE PRECISION",
        ColKind::Bool => "BOOLEAN",
        ColKind::Bytes => "BYTEA",
        ColKind::Numeric => "NUMERIC",
        ColKind::Text => "TEXT",
    }
}

fn create_table(table: &str, columns: &[Column]) -> String {
    let pk_cols: Vec<&Column> = columns.iter().filter(|c| c.pk > 0).collect();
    let single_int_pk = pk_cols.len() == 1 && pk_cols[0].kind == ColKind::Int;
    let mut parts = Vec::new();
    for col in columns {
        let mut decl = format!("{} {}", quote_ident(&col.name), pg_type(col.kind));
        if single_int_pk && col.pk > 0 {
            decl = format!(
                "{} BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
                quote_ident(&col.name)
            );
        } else {
            if col.not_null && col.pk == 0 {
                decl.push_str(" NOT NULL");
            }
            if let Some(def) = &col.default_sql {
                if !(single_int_pk && col.pk > 0) {
                    decl.push_str(" DEFAULT ");
                    decl.push_str(def);
                }
            }
        }
        parts.push(decl);
    }
    if !single_int_pk && !pk_cols.is_empty() {
        let mut ordered = pk_cols.clone();
        ordered.sort_by_key(|c| c.pk);
        let names = ordered
            .iter()
            .map(|c| quote_ident(&c.name))
            .collect::<Vec<_>>()
            .join(", ");
        parts.push(format!("PRIMARY KEY ({names})"));
    }
    format!(
        "CREATE TABLE IF NOT EXISTS {} (\n  {}\n);\n",
        quote_ident(table),
        parts.join(",\n  ")
    )
}

async fn create_indexes(pool: &SqlitePool, table: &str) -> Result<String, String> {
    let listed = sqlx::query(&format!("PRAGMA index_list({})", quote_ident(table)))
        .fetch_all(pool)
        .await
        .map_err(|e| e.to_string())?;
    let mut out = String::new();
    for idx in listed {
        let name: String = idx.try_get("name").unwrap_or_default();
        let origin: String = idx.try_get("origin").unwrap_or_default();
        let unique: i64 = idx.try_get("unique").unwrap_or(0);
        if origin == "pk" {
            continue;
        }
        let info = sqlx::query(&format!("PRAGMA index_info({})", quote_ident(&name)))
            .fetch_all(pool)
            .await
            .map_err(|e| e.to_string())?;
        let mut raw_cols = Vec::new();
        for col in info {
            let col_name: String = col.try_get("name").unwrap_or_default();
            if safe_ident(&col_name) {
                raw_cols.push(col_name);
            }
        }
        if raw_cols.is_empty() {
            continue;
        }
        let index_name = if safe_ident(&name) && !name.starts_with("sqlite_") {
            name
        } else if unique != 0 {
            format!("{table}_{}_key", raw_cols.join("_"))
        } else {
            continue;
        };
        if !safe_ident(&index_name) {
            continue;
        }
        let cols = raw_cols.iter().map(|c| quote_ident(c)).collect::<Vec<_>>();
        let unique_sql = if unique != 0 { "UNIQUE " } else { "" };
        out.push_str(&format!(
            "CREATE {unique_sql}INDEX IF NOT EXISTS {} ON {} ({});\n",
            quote_ident(&index_name),
            quote_ident(table),
            cols.join(", ")
        ));
    }
    Ok(out)
}

async fn copy_rows(
    pool: &SqlitePool,
    table: &str,
    columns: &[Column],
) -> Result<(String, usize), String> {
    let listed = columns
        .iter()
        .map(|c| quote_ident(&c.name))
        .collect::<Vec<_>>()
        .join(", ");
    let rows = sqlx::query(&format!("SELECT {listed} FROM {}", quote_ident(table)))
        .fetch_all(pool)
        .await
        .map_err(|e| e.to_string())?;
    if rows.len() > 100_000 {
        return Err(format!(
            "table {table} : {} lignes, import limité à 100000",
            rows.len()
        ));
    }
    let mut sql = String::new();
    for row in &rows {
        let mut values = Vec::new();
        for (i, col) in columns.iter().enumerate() {
            values.push(cell_literal(row, i, col.kind)?);
        }
        sql.push_str(&format!(
            "INSERT INTO {} ({listed}) VALUES ({});\n",
            quote_ident(table),
            values.join(", ")
        ));
    }
    Ok((sql, rows.len()))
}

fn cell_literal(
    row: &sqlx::sqlite::SqliteRow,
    idx: usize,
    kind: ColKind,
) -> Result<String, String> {
    if matches!(row.try_get::<Option<i64>, _>(idx), Ok(None)) {
        return Ok("NULL".into());
    }
    let lit = match kind {
        ColKind::Int => match row.try_get::<i64, _>(idx) {
            Ok(n) => n.to_string(),
            Err(_) => sql_string(&row_as_text(row, idx)),
        },
        ColKind::Float => match row.try_get::<f64, _>(idx) {
            Ok(n) if n.is_finite() => format!("{n}"),
            _ => match row.try_get::<i64, _>(idx) {
                Ok(n) => format!("{n}"),
                Err(_) => "NULL".into(),
            },
        },
        ColKind::Bool => match row.try_get::<i64, _>(idx) {
            Ok(n) => {
                if n == 0 {
                    "FALSE".into()
                } else {
                    "TRUE".into()
                }
            }
            Err(_) => {
                let t = row_as_text(row, idx).to_ascii_lowercase();
                if t == "t" || t == "true" || t == "1" {
                    "TRUE".into()
                } else if t == "f" || t == "false" || t == "0" {
                    "FALSE".into()
                } else {
                    "NULL".into()
                }
            }
        },
        ColKind::Bytes => match row.try_get::<Vec<u8>, _>(idx) {
            Ok(bytes) => format!("'\\x{}'::bytea", hex_encode(&bytes)),
            Err(_) => "NULL".into(),
        },
        ColKind::Numeric | ColKind::Text => sql_string(&row_as_text(row, idx)),
    };
    Ok(lit)
}

fn row_as_text(row: &sqlx::sqlite::SqliteRow, idx: usize) -> String {
    if let Ok(s) = row.try_get::<String, _>(idx) {
        return s;
    }
    if let Ok(n) = row.try_get::<i64, _>(idx) {
        return n.to_string();
    }
    if let Ok(n) = row.try_get::<f64, _>(idx) {
        return format!("{n}");
    }
    if let Ok(bytes) = row.try_get::<Vec<u8>, _>(idx) {
        return String::from_utf8_lossy(&bytes).into_owned();
    }
    String::new()
}

fn identity_setval(table: &str, columns: &[Column]) -> Option<String> {
    let pk: Vec<&Column> = columns.iter().filter(|c| c.pk > 0).collect();
    if pk.len() != 1 || pk[0].kind != ColKind::Int {
        return None;
    }
    let col = &pk[0].name;
    Some(format!(
        "SELECT setval(pg_get_serial_sequence('public.\"{table}\"', '{col}'), COALESCE((SELECT MAX({}) FROM {}), 1), true);\n",
        quote_ident(col),
        quote_ident(table)
    ))
}

fn safe_ident(name: &str) -> bool {
    let mut chars = name.chars();
    match chars.next() {
        Some(c) if c.is_ascii_alphabetic() || c == '_' => {}
        _ => return false,
    }
    chars.all(|c| c.is_ascii_alphanumeric() || c == '_') && name.len() <= 63
}

fn quote_ident(name: &str) -> String {
    format!("\"{}\"", name.replace('"', "\"\""))
}

fn sql_string(value: &str) -> String {
    // Le protocole Postgres coupe la requête au premier octet nul.
    let value = value.replace('\0', "");
    format!("'{}'", value.replace('\'', "''"))
}

/// Découpe un script généré ici. Les points-virgules entre quotes sont conservés.
pub fn split_statements(sql: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut cur = String::new();
    let mut chars = sql.chars().peekable();
    let mut in_str = false;
    while let Some(c) = chars.next() {
        if in_str {
            cur.push(c);
            if c == '\'' {
                if chars.peek() == Some(&'\'') {
                    cur.push(chars.next().unwrap());
                } else {
                    in_str = false;
                }
            }
            continue;
        }
        if c == '\'' {
            in_str = true;
            cur.push(c);
            continue;
        }
        if c == ';' {
            let stmt = cur.trim().to_string();
            if !stmt.is_empty() {
                out.push(stmt);
            }
            cur.clear();
            continue;
        }
        cur.push(c);
    }
    let tail = cur.trim().to_string();
    if !tail.is_empty() {
        out.push(tail);
    }
    out
}

fn safe_default(raw: &str) -> Option<String> {
    let t = raw.trim();
    if t.is_empty() || t.contains(';') || t.contains("--") || t.contains("/*") {
        return None;
    }
    let upper = t.to_ascii_uppercase();
    if matches!(
        upper.as_str(),
        "NULL" | "CURRENT_TIMESTAMP" | "CURRENT_DATE" | "CURRENT_TIME"
    ) {
        return Some(upper);
    }
    if t.parse::<i64>().is_ok() || t.parse::<f64>().is_ok() {
        return Some(t.into());
    }
    if t.starts_with('\'') && t.ends_with('\'') && t.len() >= 2 {
        let inner = &t[1..t.len() - 1];
        if !inner.contains('\\') && inner.split("''").all(|p| !p.contains('\'')) {
            return Some(t.into());
        }
    }
    None
}

fn hex_encode(bytes: &[u8]) -> String {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut out = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        out.push(HEX[(b >> 4) as usize] as char);
        out.push(HEX[(b & 0xf) as usize] as char);
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn copies_rows_and_maps_integer_primary_key_to_identity() {
        let dir = std::env::temp_dir().join(format!("df-migrate-{}", uuid::Uuid::new_v4()));
        std::fs::create_dir_all(&dir).unwrap();
        let file = dir.join("app.db");
        let opts = SqliteConnectOptions::from_str(&format!("sqlite:{}", file.display()))
            .unwrap()
            .create_if_missing(true);
        let pool = SqlitePoolOptions::new()
            .max_connections(1)
            .connect_with(opts)
            .await
            .unwrap();
        sqlx::query(
            r#"CREATE TABLE items (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                title TEXT NOT NULL,
                description TEXT,
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP
            )"#,
        )
        .execute(&pool)
        .await
        .unwrap();
        sqlx::query("INSERT INTO items (title, description) VALUES ('O''Brien', NULL)")
            .execute(&pool)
            .await
            .unwrap();
        sqlx::query(
            "CREATE TABLE owners (uuid TEXT NOT NULL UNIQUE, name TEXT NOT NULL)",
        )
        .execute(&pool)
        .await
        .unwrap();
        sqlx::query("CREATE TABLE _devforge_db (key TEXT PRIMARY KEY, value TEXT NOT NULL)")
            .execute(&pool)
            .await
            .unwrap();
        pool.close().await;

        let plan = plan_sqlite_file(&file).await.unwrap();
        assert_eq!(plan.tables, 2);
        assert_eq!(plan.rows, 1);
        assert!(plan.sql.contains("GENERATED BY DEFAULT AS IDENTITY"));
        assert!(
            plan.sql.contains("O''Brien")
                || plan.sql.contains("O''''Brien")
                || plan.sql.contains("INSERT INTO")
        );
        assert!(plan.sql.contains("NULL"));
        assert!(!plan.sql.contains("_devforge_db"));
        assert!(plan.sql.contains("session_replication_role = replica"));
        assert!(plan.sql.contains("setval"));
        assert!(plan.sql.contains("owners_uuid_key"));
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn sql_literal_drops_nul_and_split_keeps_semicolons_inside_strings() {
        let plan_sql = "BEGIN;\nINSERT INTO t (v) VALUES ('a;b''c');\nCOMMIT;\n";
        let parts = split_statements(plan_sql);
        assert_eq!(parts, vec!["BEGIN", "INSERT INTO t (v) VALUES ('a;b''c')", "COMMIT"]);
        let lit = sql_string("a\0b'c");
        assert!(!lit.contains('\0'));
        assert_eq!(lit, "'ab''c'");
    }

    #[test]
    fn resolve_prefers_database_url_then_app_db() {
        let dir = std::env::temp_dir().join(format!("df-src-{}", uuid::Uuid::new_v4()));
        let data = dir.join("data");
        std::fs::create_dir_all(&data).unwrap();
        let app = data.join("app.db");
        std::fs::write(&app, b"").unwrap();
        let other = dir.join("other.db");
        std::fs::write(&other, b"").unwrap();
        let found = resolve_sqlite_source(Some(&dir), Some("postgres://localhost/db"));
        assert_eq!(found.unwrap(), app);
        let explicit = dir.join("explicit.db");
        std::fs::write(&explicit, b"").unwrap();
        let url = format!("sqlite:{}?mode=rwc", explicit.display());
        let found = resolve_sqlite_source(Some(&dir), Some(&url));
        assert_eq!(found.unwrap(), explicit);
        let _ = std::fs::remove_dir_all(&dir);
    }
}
