use serde::{Deserialize, Serialize};
use serde_json::{json, Value};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CatalogField {
    pub key: String,
    pub label: String,
    pub placeholder: Option<String>,
    pub secret: bool,
    pub required: bool,
    pub help: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CatalogPreset {
    pub id: String,
    pub name: String,
    pub description: String,
    pub category: String,
    pub docs_url: Option<String>,
    pub default_url: Option<String>,
    pub fields: Vec<CatalogField>,
    /// e.g. "database" — enables resource linking UI
    pub resource_kind: Option<String>,
    pub popular: bool,
}

fn field(
    key: &str,
    label: &str,
    secret: bool,
    required: bool,
    placeholder: Option<&str>,
    help: Option<&str>,
) -> CatalogField {
    CatalogField {
        key: key.into(),
        label: label.into(),
        placeholder: placeholder.map(str::to_string),
        secret,
        required,
        help: help.map(str::to_string),
    }
}

/// Catalogue MCP / intégrations utiles pour DevForge.
pub fn catalog() -> Vec<CatalogPreset> {
    vec![
        CatalogPreset {
            id: "turso".into(),
            name: "Turso".into(),
            description:
                "Bases libSQL edge. Liste tes DBs et relie-les à un projet (env DATABASE_URL)."
                    .into(),
            category: "database".into(),
            docs_url: Some("https://docs.turso.tech/mcp".into()),
            default_url: Some("https://mcp.turso.tech/mcp".into()),
            fields: vec![
                field(
                    "api_token",
                    "Platform API Token",
                    true,
                    true,
                    Some("eyJ…"),
                    Some("Turso → Account → API Tokens"),
                ),
                field(
                    "org",
                    "Organization slug",
                    false,
                    true,
                    Some("mon-org"),
                    Some("Slug affiché dans le dashboard Turso"),
                ),
            ],
            resource_kind: Some("database".into()),
            popular: true,
        },
        CatalogPreset {
            id: "cloudflare".into(),
            name: "Cloudflare".into(),
            description:
                "Workers, DNS, R2, D1, Pages — MCP officiel Cloudflare (API token)."
                    .into(),
            category: "infrastructure".into(),
            docs_url: Some(
                "https://developers.cloudflare.com/agents/model-context-protocol/mcp-servers-for-cloudflare/"
                    .into(),
            ),
            default_url: Some("https://mcp.cloudflare.com/mcp".into()),
            fields: vec![
                field(
                    "api_token",
                    "API Token",
                    true,
                    true,
                    Some("…"),
                    Some("dash.cloudflare.com → My Profile → API Tokens"),
                ),
                field(
                    "account_id",
                    "Account ID (optionnel)",
                    false,
                    false,
                    Some("32 hex chars"),
                    Some("Utile si plusieurs comptes ; sinon auto-détecté"),
                ),
                field(
                    "url",
                    "URL MCP",
                    false,
                    false,
                    Some("https://mcp.cloudflare.com/mcp"),
                    Some("Par défaut : MCP API Cloudflare"),
                ),
            ],
            resource_kind: None,
            popular: true,
        },
        CatalogPreset {
            id: "vercel".into(),
            name: "Vercel".into(),
            description: "Déploiements, projets et domaines Vercel.".into(),
            category: "infrastructure".into(),
            docs_url: Some("https://vercel.com/docs".into()),
            default_url: None,
            fields: vec![
                field(
                    "api_token",
                    "Access Token",
                    true,
                    true,
                    Some("…"),
                    Some("Vercel → Settings → Tokens"),
                ),
                field(
                    "team_id",
                    "Team ID (optionnel)",
                    false,
                    false,
                    Some("team_…"),
                    None,
                ),
                field(
                    "url",
                    "URL MCP (optionnel)",
                    false,
                    false,
                    Some("http://127.0.0.1:3600/mcp"),
                    None,
                ),
            ],
            resource_kind: None,
            popular: true,
        },
        CatalogPreset {
            id: "supabase".into(),
            name: "Supabase".into(),
            description: "Postgres, Auth et Storage Supabase.".into(),
            category: "database".into(),
            docs_url: Some("https://supabase.com/docs".into()),
            default_url: None,
            fields: vec![
                field(
                    "access_token",
                    "Personal Access Token",
                    true,
                    true,
                    Some("sbp_…"),
                    Some("Supabase → Account → Access Tokens"),
                ),
                field(
                    "project_ref",
                    "Project ref (optionnel)",
                    false,
                    false,
                    Some("abcdefghijklmnop"),
                    None,
                ),
                field(
                    "url",
                    "URL MCP (optionnel)",
                    false,
                    false,
                    Some("http://127.0.0.1:3700/mcp"),
                    None,
                ),
            ],
            resource_kind: Some("database".into()),
            popular: true,
        },
        CatalogPreset {
            id: "neon".into(),
            name: "Neon".into(),
            description: "Postgres serverless Neon.".into(),
            category: "database".into(),
            docs_url: Some("https://neon.tech/docs".into()),
            default_url: None,
            fields: vec![
                field(
                    "api_key",
                    "API Key",
                    true,
                    true,
                    Some("napi_…"),
                    Some("Neon Console → Account → API Keys"),
                ),
                field(
                    "url",
                    "URL MCP (optionnel)",
                    false,
                    false,
                    Some("http://127.0.0.1:3800/mcp"),
                    None,
                ),
            ],
            resource_kind: Some("database".into()),
            popular: true,
        },
        CatalogPreset {
            id: "upstash".into(),
            name: "Upstash".into(),
            description: "Redis / QStash Upstash.".into(),
            category: "database".into(),
            docs_url: Some("https://upstash.com/docs".into()),
            default_url: None,
            fields: vec![
                field(
                    "api_key",
                    "API Key",
                    true,
                    true,
                    Some("…"),
                    Some("Upstash Console → Account → API Keys"),
                ),
                field(
                    "email",
                    "Account email",
                    false,
                    true,
                    Some("you@example.com"),
                    None,
                ),
                field(
                    "url",
                    "URL MCP (optionnel)",
                    false,
                    false,
                    Some("http://127.0.0.1:3900/mcp"),
                    None,
                ),
            ],
            resource_kind: None,
            popular: false,
        },
        CatalogPreset {
            id: "slack".into(),
            name: "Slack".into(),
            description: "Notifications, canaux et tools Slack via MCP.".into(),
            category: "messaging".into(),
            docs_url: Some("https://api.slack.com/apps".into()),
            default_url: None,
            fields: vec![
                field(
                    "bot_token",
                    "Bot User OAuth Token",
                    true,
                    true,
                    Some("xoxb-…"),
                    Some("Slack App → OAuth & Permissions"),
                ),
                field(
                    "url",
                    "URL MCP (optionnel)",
                    false,
                    false,
                    Some("http://127.0.0.1:3100/mcp"),
                    Some("Si tu exposes un serveur MCP Slack local ou distant"),
                ),
            ],
            resource_kind: None,
            popular: true,
        },
        CatalogPreset {
            id: "linear".into(),
            name: "Linear".into(),
            description: "Issues et projets Linear pour les agents.".into(),
            category: "productivity".into(),
            docs_url: Some("https://linear.app/docs".into()),
            default_url: None,
            fields: vec![
                field("api_key", "API Key", true, true, Some("lin_api_…"), None),
                field(
                    "url",
                    "URL MCP (optionnel)",
                    false,
                    false,
                    Some("http://127.0.0.1:3200/mcp"),
                    None,
                ),
            ],
            resource_kind: None,
            popular: true,
        },
        CatalogPreset {
            id: "sentry".into(),
            name: "Sentry".into(),
            description: "Erreurs et releases Sentry.".into(),
            category: "observability".into(),
            docs_url: Some("https://docs.sentry.io".into()),
            default_url: None,
            fields: vec![
                field("auth_token", "Auth Token", true, true, Some("sntrys_…"), None),
                field("org", "Organization slug", false, true, Some("mon-org"), None),
                field(
                    "url",
                    "URL MCP (optionnel)",
                    false,
                    false,
                    Some("http://127.0.0.1:3300/mcp"),
                    None,
                ),
            ],
            resource_kind: None,
            popular: true,
        },
        CatalogPreset {
            id: "resend".into(),
            name: "Resend".into(),
            description: "Envoi d’emails transactionnels.".into(),
            category: "messaging".into(),
            docs_url: Some("https://resend.com/docs".into()),
            default_url: None,
            fields: vec![
                field(
                    "api_key",
                    "API Key",
                    true,
                    true,
                    Some("re_…"),
                    Some("Resend → API Keys"),
                ),
                field(
                    "url",
                    "URL MCP (optionnel)",
                    false,
                    false,
                    Some("http://127.0.0.1:4000/mcp"),
                    None,
                ),
            ],
            resource_kind: None,
            popular: false,
        },
        CatalogPreset {
            id: "posthog".into(),
            name: "PostHog".into(),
            description: "Product analytics et feature flags.".into(),
            category: "observability".into(),
            docs_url: Some("https://posthog.com/docs".into()),
            default_url: None,
            fields: vec![
                field(
                    "api_key",
                    "Personal API Key",
                    true,
                    true,
                    Some("phx_…"),
                    None,
                ),
                field(
                    "host",
                    "Host",
                    false,
                    false,
                    Some("https://eu.posthog.com"),
                    Some("US ou EU selon ton projet"),
                ),
                field(
                    "url",
                    "URL MCP (optionnel)",
                    false,
                    false,
                    Some("http://127.0.0.1:4100/mcp"),
                    None,
                ),
            ],
            resource_kind: None,
            popular: false,
        },
        CatalogPreset {
            id: "discord".into(),
            name: "Discord".into(),
            description: "Bots et notifications Discord.".into(),
            category: "messaging".into(),
            docs_url: Some("https://discord.com/developers/docs".into()),
            default_url: None,
            fields: vec![
                field(
                    "bot_token",
                    "Bot Token",
                    true,
                    true,
                    Some("…"),
                    Some("Discord Developer Portal → Bot"),
                ),
                field(
                    "url",
                    "URL MCP (optionnel)",
                    false,
                    false,
                    Some("http://127.0.0.1:4200/mcp"),
                    None,
                ),
            ],
            resource_kind: None,
            popular: false,
        },
        CatalogPreset {
            id: "railway".into(),
            name: "Railway".into(),
            description: "Projets et services Railway.".into(),
            category: "infrastructure".into(),
            docs_url: Some("https://docs.railway.app".into()),
            default_url: None,
            fields: vec![
                field(
                    "api_token",
                    "API Token",
                    true,
                    true,
                    Some("…"),
                    Some("Railway → Account → Tokens"),
                ),
                field(
                    "url",
                    "URL MCP (optionnel)",
                    false,
                    false,
                    Some("http://127.0.0.1:4300/mcp"),
                    None,
                ),
            ],
            resource_kind: None,
            popular: false,
        },
        CatalogPreset {
            id: "notion".into(),
            name: "Notion".into(),
            description: "Pages et bases Notion.".into(),
            category: "productivity".into(),
            docs_url: Some("https://developers.notion.com".into()),
            default_url: None,
            fields: vec![
                field(
                    "integration_token",
                    "Integration Token",
                    true,
                    true,
                    Some("ntn_…"),
                    None,
                ),
                field(
                    "url",
                    "URL MCP (optionnel)",
                    false,
                    false,
                    Some("http://127.0.0.1:3400/mcp"),
                    None,
                ),
            ],
            resource_kind: None,
            popular: false,
        },
        CatalogPreset {
            id: "stripe".into(),
            name: "Stripe".into(),
            description: "Paiements, clients et webhooks Stripe.".into(),
            category: "payments".into(),
            docs_url: Some("https://docs.stripe.com".into()),
            default_url: None,
            fields: vec![
                field(
                    "secret_key",
                    "Secret Key",
                    true,
                    true,
                    Some("sk_live_… / sk_test_…"),
                    None,
                ),
                field(
                    "url",
                    "URL MCP (optionnel)",
                    false,
                    false,
                    Some("http://127.0.0.1:3500/mcp"),
                    None,
                ),
            ],
            resource_kind: None,
            popular: true,
        },
        CatalogPreset {
            id: "github".into(),
            name: "GitHub MCP".into(),
            description: "Tools GitHub dédiés (en plus de la connexion PAT Settings).".into(),
            category: "devops".into(),
            docs_url: Some("https://github.com/github/github-mcp-server".into()),
            default_url: None,
            fields: vec![
                field(
                    "token",
                    "Personal Access Token",
                    true,
                    true,
                    Some("ghp_…"),
                    None,
                ),
                field(
                    "url",
                    "URL MCP",
                    false,
                    true,
                    Some("http://127.0.0.1:3001/mcp"),
                    Some("Endpoint de ton github-mcp-server"),
                ),
            ],
            resource_kind: None,
            popular: false,
        },
        CatalogPreset {
            id: "custom".into(),
            name: "MCP custom".into(),
            description: "Brancher n’importe quel serveur MCP HTTP.".into(),
            category: "other".into(),
            docs_url: None,
            default_url: None,
            fields: vec![
                field("name", "Nom", false, true, Some("Mon MCP"), None),
                field(
                    "url",
                    "URL",
                    false,
                    true,
                    Some("http://127.0.0.1:9000/mcp"),
                    None,
                ),
                field(
                    "auth_header",
                    "Authorization (optionnel)",
                    true,
                    false,
                    Some("Bearer …"),
                    None,
                ),
            ],
            resource_kind: None,
            popular: false,
        },
    ]
}

pub fn catalog_as_json() -> Value {
    json!({ "data": catalog() })
}

pub fn find_preset(id: &str) -> Option<CatalogPreset> {
    catalog().into_iter().find(|p| p.id == id)
}
