import Database from 'better-sqlite3';
import { existsSync, mkdirSync } from 'fs';
import { join } from 'path';

const dataDir = join(process.cwd(), 'data');

function isPostgres(url: string | undefined): url is string {
  return !!url && /^postgres(ql)?:\/\//i.test(url);
}

type PgSql = import('postgres').Sql;

let pgClient: PgSql | null = null;

async function pg(): Promise<PgSql> {
  const url = process.env.DATABASE_URL?.trim();
  if (!isPostgres(url)) {
    throw new Error('DATABASE_URL postgres manquante');
  }
  if (!pgClient) {
    const postgres = (await import('postgres')).default;
    pgClient = postgres(url, { max: 4 });
    await pgClient`
      CREATE TABLE IF NOT EXISTS items (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title TEXT NOT NULL,
        description TEXT,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP
      )
    `;
    const rows = await pgClient`SELECT COUNT(*)::int AS count FROM items`;
    const count = Number(rows[0]?.count ?? 0);
    if (count === 0) {
      await pgClient`
        INSERT INTO items (title, description) VALUES
          ('Exemple 1', 'Premier élément de démo'),
          ('Exemple 2', 'Deuxième élément avec PostgreSQL'),
          ('Exemple 3', 'Troisième élément pour tester')
      `;
    }
  }
  return pgClient;
}

/** `DATABASE_URL=sqlite:data/app.db?mode=rwc` (posé au scaffold) ou `data/app.db`. */
function resolveDbPath(): string {
  const fromEnv = process.env.DATABASE_URL?.trim();
  if (fromEnv && !isPostgres(fromEnv)) {
    const stripped = fromEnv.replace(/^sqlite:/i, '').split('?')[0]?.trim();
    if (stripped) return stripped;
  }
  return join(dataDir, 'app.db');
}

function sqlite() {
  if (!existsSync(dataDir)) {
    mkdirSync(dataDir, { recursive: true });
  }
  const dbPath = resolveDbPath();
  const dbDir = join(dbPath, '..');
  if (!existsSync(dbDir)) {
    mkdirSync(dbDir, { recursive: true });
  }
  const db = new Database(dbPath);
  db.exec(`
    CREATE TABLE IF NOT EXISTS items (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      title TEXT NOT NULL,
      description TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )
  `);
  const count = db.prepare('SELECT COUNT(*) as count FROM items').get() as { count: number };
  if (count.count === 0) {
    const insert = db.prepare('INSERT INTO items (title, description) VALUES (?, ?)');
    insert.run('Exemple 1', 'Premier élément de démo');
    insert.run('Exemple 2', 'Deuxième élément avec SQLite');
    insert.run('Exemple 3', 'Troisième élément pour tester');
  }
  return db;
}

let sqliteDb: ReturnType<typeof sqlite> | null = null;

function sqliteHandle() {
  if (!sqliteDb) sqliteDb = sqlite();
  return sqliteDb;
}

export interface Item {
  id: number;
  title: string;
  description: string | null;
  created_at: string;
}

export async function getAllItems(): Promise<Item[]> {
  if (isPostgres(process.env.DATABASE_URL?.trim())) {
    const sql = await pg();
    return await sql<Item[]>`
      SELECT id, title, description, created_at::text AS created_at
      FROM items ORDER BY created_at DESC
    `;
  }
  return sqliteHandle().prepare('SELECT * FROM items ORDER BY created_at DESC').all() as Item[];
}

export async function getItemById(id: number): Promise<Item | undefined> {
  if (isPostgres(process.env.DATABASE_URL?.trim())) {
    const sql = await pg();
    const rows = await sql<Item[]>`
      SELECT id, title, description, created_at::text AS created_at
      FROM items WHERE id = ${id}
    `;
    return rows[0];
  }
  return sqliteHandle().prepare('SELECT * FROM items WHERE id = ?').get(id) as Item | undefined;
}

export async function createItem(title: string, description?: string): Promise<Item> {
  if (isPostgres(process.env.DATABASE_URL?.trim())) {
    const sql = await pg();
    const rows = await sql<Item[]>`
      INSERT INTO items (title, description)
      VALUES (${title}, ${description ?? null})
      RETURNING id, title, description, created_at::text AS created_at
    `;
    return rows[0];
  }
  const db = sqliteHandle();
  const result = db
    .prepare('INSERT INTO items (title, description) VALUES (?, ?)')
    .run(title, description || null);
  return (await getItemById(result.lastInsertRowid as number))!;
}
