[package]
name = "devforge-domain"
version.workspace = true
edition.workspace = true

[dependencies]
devforge-shared = { workspace = true }
devforge-deploy = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
