export {
    applyAppearance,
    applyStoredAppearance,
    applyTheme,
    contentWidthClass,
    getAppearancePreferences,
    getInitialTheme,
    getStoredThemePreference,
    setThemePreference,
    toggleResolvedTheme,
    type AppearancePreferences,
    type PageWidth,
    type Theme,
    type ThemePreference,
    type ZoomLevel,
} from './appearance';
